In [2]:
import numpy as np
import math

# Main Function

 In this method, we take the user's light out matrix to solve it by row reduction

In [3]:
def main():
    default_matrix = np.array([[1, 0, 0, 0, 1],
                               [0, 1, 0, 1, 0],
                               [0, 0, 1, 0, 0],
                               [0, 1, 0, 1, 0],
                               [1, 0, 0, 0, 1]])
    deafault_dim = 5
    while True :
        print("Hello, welcome to light out solver!\nPlease select the option you want:\n1) Default Matrix\n2)new matrix")
        print("Default Matrix:\n" , default_matrix)
        choice = input()
        if choice == "1" : make_matrix_for_solver(default_matrix , deafault_dim)
        elif choice == "2" :
            new_dimention = int(input("Please enter matrix dimention:"))
            new_matrix = np.arange(0,int(math.pow(new_dimention , 2))).reshape(new_dimention,new_dimention)*0
            for xIndex in range(0,new_matrix.shape[0]):
               for yIndex in range(0,new_matrix.shape[0]): 
                        new_element =  int(input(f" please enter your new element [{xIndex},{yIndex}]"))
                        new_matrix[xIndex,yIndex] = new_element
            print("\nNew Matrix :\n" , new_matrix)
            make_matrix_for_solver(new_matrix,new_dimention)
        else : break

# Make Agmented Matrix Function

In this function we form the agmeneted matrix. To solve this problem, we must pay attention to the dimensions of the input matrix, which is n * n, and based on this we have n * n Boolean equation, each of which forms a row of our matrix, and each of them represents the effect of compression of that house in the game. It is light out, so if a element is one, it means that by pressing the row(n) house, we will have a change in the brightness of that element house.

In [4]:
def  make_matrix_for_solver(game_matrix , dim):
    dim_square = int(math.pow(dim , 2))
    solver_matrix = np.arange(0,dim_square*(dim_square+1)).reshape(dim_square,dim_square+1)*0
    solver_matrix[:,dim_square] = game_matrix.ravel().tolist()
    
    for index in range(0,dim_square):
        solver_matrix[index , index ] = 1
        above_index = index - dim
        if above_index >= 0 : solver_matrix[index , above_index ] = 1
        next_row_index = index + dim
        if  next_row_index <= dim_square : solver_matrix[index , next_row_index ] = 1
        remind_left_right = index % dim
        if remind_left_right != 0 : solver_matrix[index , index -1 ] = 1
        if remind_left_right != dim-1 : solver_matrix[index , index + 1 ] = 1
    print("\nAgmented Matrix:\n" , solver_matrix)    
    echlon_matrix(solver_matrix)

# Echlon Matrix Function

In [5]:
def echlon_matrix(solver_matrix):
    for row_index in range(0,solver_matrix.shape[0]) :
        solver_matrix = swap_zero_piviot(solver_matrix,row_index)
        for second_row_index in range(row_index+1,solver_matrix.shape[0]): 
            if (solver_matrix[second_row_index,row_index] == 1) :
                solver_matrix[second_row_index,:] = xor_matrix_func(solver_matrix,second_row_index,row_index)
    print("Echlon Matrix:\n",solver_matrix)
    reduced_echlon(solver_matrix)
        

# Xor Matrix Funcion

In this function, we have to XOR the two rows of the matrix together to reduce the row , which is simple to implement, and based on the value of each row  with an piviot position, the operation is performed.If the first element is zero we know that the result is the element value of second row, so there is practically no need to define the condition, and only when we are on the one-sided element with the number one, our output is the opposite of the second number that we wrote in the condition.

In [6]:
def xor_matrix_func(solver_matrix,second_row_index,row_index):
    for col_index in range(0,solver_matrix.shape[1]):
        if solver_matrix[row_index,col_index] :
            if (solver_matrix[second_row_index,col_index] == 0 ): solver_matrix[second_row_index,col_index] = 1
            else : solver_matrix[second_row_index,col_index] = 0
    return solver_matrix[second_row_index,:] 

# Swap Zero Piviot function

In this function, we check the row reduction to continue correctly, so that if the piviot position of our diameter is zero, we should replace it with the first row lower than itself, which is one in that piviot position.

In [7]:
def swap_zero_piviot(solver_matrix,index):
    if index < solver_matrix.shape[0] :
      if solver_matrix[index,index] != 1 :
        for current_row_index in range(index+1,solver_matrix.shape[0]) :
            if solver_matrix[current_row_index,index] : 
                temp = np.matrix(solver_matrix[index])
                solver_matrix[index] = solver_matrix[current_row_index]
                solver_matrix[current_row_index] = np.array(temp)
                break
                
    return  solver_matrix  

In [8]:
def reduced_echlon(solver_matrix):
    for row_index in range(solver_matrix.shape[0]-1,-1,-1) :
        
        for second_row_index in range(row_index-1,-1,-1):
            if (solver_matrix[second_row_index,row_index] == 1) :
                solver_matrix[second_row_index,:] = xor_matrix_func(solver_matrix,second_row_index,row_index)
    print("Reduced Echlon:\n",solver_matrix)
    show_resualt(solver_matrix)

# Lets Show The Result of The Game

In [9]:
def show_resualt(solver_matrix):
     solved = True
     for row_index in range(0,solver_matrix.shape[0]) :
            if np.sum(solver_matrix[row_index,0:solver_matrix.shape[1]-2]) == 0 and solver_matrix[row_index,solver_matrix.shape[1]-1] == 1 : 
                print("This solution cannot be resolved ")
                solved = False
                break
    
     if solved :
        dimention_of_resualt = int(math.sqrt(solver_matrix.shape[0]))
        solved_map = solver_matrix[:,solver_matrix.shape[1]-1].reshape(dimention_of_resualt,dimention_of_resualt)
        print("Solved Map:\n1 --> press for solving\n",solved_map)
        print("index map\n(each home index that you should press for solving game!)\n",
                      np.arange(1,solver_matrix.shape[0]+1).reshape(solved_map.shape[0],solved_map.shape[0]))

In [11]:
main()

Hello, welcome to light out solver!
Please select the option you want:
1) Default Matrix
2)new matrix
Default Matrix:
 [[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]]
1

Agmented Matrix:
 [[1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 